module.exports=
{
    naidu:function(){
        return("muthwaala");
    }
    ,
    kanna:function(){
        return("tanu")
    },
    vamsi:function(){
        return("kadilya");
    }
}